### PR TITLE
Wrong TARGET_CPU_VARIANT

### PR DESCRIPTION
**Pull request by Nothing-Dev**
jagnm is cortex-a7 not krait

### CODE REVIEW

**Comment by vm03** [comment]
msm8226 is krait SOC
https://en.wikipedia.org/wiki/Krait_%28CPU%29
https://github.com/CyanogenMod/android_device_samsung_msm8226-common/blob/cm-12.0/BoardConfigCommon.mk#L23
https://github.com/CyanogenMod/android_device_motorola_msm8226-common/blob/cm-12.1/BoardConfigCommon.mk#L35

**Comment by Nothing-Dev** [comment]
Jagnm is msm8926, but in source, is msm8226 for compatibility.

http://system-on-a-chip.specout.com/l/432/Qualcomm-Snapdragon-400-MSM8926

**Comment by vm03** [comment]
8926 has LTE modem, another same with 8226.

**Comment by Nothing-Dev** [comment]
But 8926 is Cortex-a7

**Comment by vm03** [comment]
proof?

**Comment by Nothing-Dev** [comment]
http://system-on-a-chip.specout.com/l/432/Qualcomm-Snapdragon-400-MSM8926

captura de pantalla de 2015-10-27 16 54 00

**Comment by vm03** [comment]
Bad proof. For example this site don't know about 8226.

**Comment by nikich340** [comment]
Hmm, it's interesting question.
These sites write that msm8x26 has cortex-a7 processor:
https://ru.m.wikipedia.org/wiki/Snapdragon
www.notebookcheck-ru.com/Qualcomm-Snapdragon-400-MSM8226-Processor.113577.0.html

On the official qcom site it's writing "Up to 1.7 GHz dual-core Qualcomm® Krait™ 300 CPU or up to 1.6GHz quad-core ARM® Cortex™ A7 CPU":
https://www.qualcomm.com/products/snapdragon/processors/400

But I don't think that by changing this flag you will see any differences. In /build it only configures dex2oat.

**Comment by vm03** [comment]
http://review.cyanogenmod.org/#/c/72024/

**Comment by nikich340** [comment]
More important: https://www.codeaurora.org/cgit/quic/la/platform/vendor/qcom/msm8226/tree/BoardConfig.mk?h=LA.BF.1.1.1.c1_rb1#n35
:)

**Pull request closed without merging**
